# This is a basic workflow to help you get started with Actions

name: Verify muster completion

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
  - cron: "0,30 12,13 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Installing our dependincies
      - name: Install Dependencies
        run: pip install -r requirements.txt

      # Creating credentials.json
      - name: Create credentials.json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "credentials.json"
          json: ${{ secrets.CREDENTIALS}}

      # Creating token.json
      - name: Create token.json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "token.json"
          json: ${{ secrets.TOKEN}}

      # Running our python script
      - name: Running Email Check
        run: python src/main.py ${{ secrets.TWILIO_SID }} ${{ secrets.TWILIO_TOKEN }} ${{ secrets.TWILIO_PHONE_NUMBER }} ${{ secrets.MY_PHONE_NUMBER }}
      
