name: Linting with flake8

on: 
  push:
  pull_request:

  workflow_dispatch:

jobs:
  flake8-lint:
    runs-on: ubuntu-latest

    name: Lint with flake8
    steps:
      # Checking out this repository
      - name: Check out source repository
        uses: actions/checkout@v3

      # Setting up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Running flake8
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          path: "src"
          max-line-length: "150"